# NixOS module for native Zwift
{ zwift-package }:
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.programs.zwift;
  inherit (lib) mkEnableOption mkOption types mkIf;
in
{
  options.programs.zwift = {
    enable = mkEnableOption "Zwift on Linux (native)";

    package = mkOption {
      type = types.package;
      default = zwift-package;
      description = "The Zwift package to use.";
    };

    zwiftUsername = mkOption {
      type = types.str;
      default = "";
      description = "Zwift account email for automatic login.";
    };

    zwiftPassword = mkOption {
      type = types.str;
      default = "";
      description = ''
        Zwift account password for automatic login.
        Consider using a secrets management solution instead of storing passwords in your config.
      '';
    };

    winePrefix = mkOption {
      type = types.str;
      default = "";
      description = ''
        Custom Wine prefix directory.
        Defaults to ~/.wine-zwift if not specified.
      '';
    };

    zwiftWorkoutDir = mkOption {
      type = types.str;
      default = "";
      description = "Custom directory for Zwift workouts.";
    };

    zwiftActivityDir = mkOption {
      type = types.str;
      default = "";
      description = "Custom directory for Zwift activities.";
    };

    zwiftLogDir = mkOption {
      type = types.str;
      default = "";
      description = "Custom directory for Zwift logs.";
    };

    zwiftScreenshotsDir = mkOption {
      type = types.str;
      default = "";
      description = "Custom directory for Zwift screenshots.";
    };

    zwiftOverrideGraphics = mkOption {
      type = types.bool;
      default = false;
      description = "Use custom graphics configuration.";
    };

    zwiftOverrideResolution = mkOption {
      type = types.str;
      default = "";
      example = "1920x1080";
      description = "Override the Zwift display resolution.";
    };

    zwiftFg = mkOption {
      type = types.bool;
      default = false;
      description = "Run Zwift in foreground mode.";
    };

    zwiftNoGameMode = mkOption {
      type = types.bool;
      default = false;
      description = "Disable GameMode integration.";
    };

    wineExperimentalWayland = mkOption {
      type = types.bool;
      default = false;
      description = "Enable experimental Wayland support in Wine.";
    };

    debug = mkOption {
      type = types.bool;
      default = false;
      description = "Enable debug output.";
    };
  };

  config = mkIf cfg.enable {
    environment.systemPackages = [ cfg.package ];

    # Create a wrapper script with configured environment variables
    environment.etc."zwift/config".text = ''
      # Zwift configuration (auto-generated by NixOS module)
      ${lib.optionalString (cfg.zwiftUsername != "") "export ZWIFT_USERNAME=\"${cfg.zwiftUsername}\""}
      ${lib.optionalString (cfg.zwiftPassword != "") "export ZWIFT_PASSWORD=\"${cfg.zwiftPassword}\""}
      ${lib.optionalString (cfg.winePrefix != "") "export WINEPREFIX=\"${cfg.winePrefix}\""}
      ${lib.optionalString (cfg.zwiftWorkoutDir != "") "export ZWIFT_WORKOUT_DIR=\"${cfg.zwiftWorkoutDir}\""}
      ${lib.optionalString (cfg.zwiftActivityDir != "") "export ZWIFT_ACTIVITY_DIR=\"${cfg.zwiftActivityDir}\""}
      ${lib.optionalString (cfg.zwiftLogDir != "") "export ZWIFT_LOG_DIR=\"${cfg.zwiftLogDir}\""}
      ${lib.optionalString (cfg.zwiftScreenshotsDir != "") "export ZWIFT_SCREENSHOTS_DIR=\"${cfg.zwiftScreenshotsDir}\""}
      ${lib.optionalString cfg.zwiftOverrideGraphics "export ZWIFT_OVERRIDE_GRAPHICS=1"}
      ${lib.optionalString (cfg.zwiftOverrideResolution != "") "export ZWIFT_OVERRIDE_RESOLUTION=\"${cfg.zwiftOverrideResolution}\""}
      ${lib.optionalString cfg.zwiftFg "export ZWIFT_FG=1"}
      ${lib.optionalString cfg.zwiftNoGameMode "export ZWIFT_NO_GAMEMODE=1"}
      ${lib.optionalString cfg.wineExperimentalWayland "export WINE_EXPERIMENTAL_WAYLAND=1"}
      ${lib.optionalString cfg.debug "export DEBUG=1"}
    '';
  };
}
