---
version: 2
updates:
- package-ecosystem: bundler
  directory: /docs
  schedule:
    interval: weekly
    day: sunday
    time: !!str 05:17
    timezone: UTC
  groups:
    documentation-site:
      patterns:
      - '*'
- package-ecosystem: docker
  directory: /src
  schedule:
    interval: weekly
    day: sunday
    time: !!str 05:17
    timezone: UTC
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: sunday
    time: !!str 05:17
    timezone: UTC
- package-ecosystem: nix
  directory: /
  schedule:
    interval: weekly
    day: sunday
    time: !!str 05:17
    timezone: UTC
