---
name: Help (Not Launching)
description: When zwift won't run or launch properly.
title: '[HELP (Not Launching/ Crashing)]'
labels: Support
body:
- type: markdown
  attributes:
    value: Before you open a new issue, search through the existing issues to see if others have had the same problem.
- type: checkboxes
  attributes:
    label: Checklist
    options:
    - label: I have given details of my install including Distribution, Wayland/ XOrg, Parameters Used, echo $XAUTHORITY, etc.
      required: true
    - label: I have provided logs showing any errors, if available (use `DEBUG=1 zwift`)
      required: true
    - label: I have filled out the issue template to the best of my ability.
      required: true
    - label: This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
      required: true
    - label: This issue is not a duplicate issue of previous issue.
- type: textarea
  attributes:
    label: Describe the issue
    description: A clear and concise description of what the issue is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Distribution Details
    description: >
      Detail your distribution, whether you are using XOrg or Wayland, Any Variables to launch zwift and also check `echo
      $XAUTHORITY` from a terminal.
- type: textarea
  attributes:
    label: Reproduction steps
    description: Without steps to reproduce, it will be hard to fix, it is very important that you fill out this part.
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: true
