source 'https://rubygems.org'

gem "jekyll", "~> 4.4.1"
gem "jekyll-coffeescript"
gem "jekyll-default-layout"
gem "jekyll-gist"
gem "jekyll-github-metadata"
gem "jekyll-optional-front-matter"
gem "jekyll-paginate"
gem "jekyll-readme-index"
gem "jekyll-titles-from-headings"
gem "jekyll-relative-links"
gem "jemoji"
gem "just-the-docs"
