name: Validate markdown
on:
  pull_request:
    paths:
      - 'README.md'
  push:
    paths:
      - 'README.md'
jobs:
  validate-readme-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5
      - name: Check README.md file for errors
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          config: '.markdownlint-cli2.jsonc'
  spellcheck-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5
      - name: Spellcheck README.md
        uses: streetsidesoftware/cspell-action@v7
        with:
          config: '.cspell.json'
          suggestions: true
